# Generated by Django 3.1.1 on 2020-11-27 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='number1',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='addition',
            old_name='number2',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='addition',
            old_name='result',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='addition',
            name='timstamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
