# Generated by Django 3.1.1 on 2020-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20201127_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='timstamp',
            field=models.TextField(),
        ),
    ]
